{{- if and .Values.secret.enabled (not .Values.existingSecret.name) }}
{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.secretName" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
