apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "openclaw.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "openclaw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "openclaw.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openclaw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.gateway .Values.gateway.controlUi .Values.gateway.controlUi.allowInsecureAuth }}
      initContainers:
      - name: gateway-config
        image: {{ .Values.gateway.initImage | default "imega/jq:1.6" | quote }}
        {{- if .Values.persistence.enabled }}
        command: ["sh", "-c", "mkdir -p /data/.openclaw && if [ -f /data/.openclaw/openclaw.json ]; then jq '.gateway.controlUi.allowInsecureAuth = true' /data/.openclaw/openclaw.json > /tmp/out && mv /tmp/out /data/.openclaw/openclaw.json; else echo '{\"gateway\":{\"controlUi\":{\"allowInsecureAuth\":true}}}' > /data/.openclaw/openclaw.json; fi"]
        volumeMounts:
        - name: data
          mountPath: {{ .Values.env.DATA_DIR | default "/data" }}
        {{- else }}
        command: ["sh", "-c", "cp /config-source/openclaw.json /openclaw-config/openclaw.json"]
        volumeMounts:
        - name: gateway-config-source
          mountPath: /config-source
          readOnly: true
        - name: openclaw-config
          mountPath: /openclaw-config
        {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        # Add replica index from StatefulSet pod name (extracts ordinal: name-0 -> 0, name-1 -> 1, etc.)
        - name: STATEFULSET_REPLICA_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Helper: Full pod name for applications that need it
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- include "openclaw.envVars" . | nindent 8 }}
        {{- if or .Values.envFromConfigMap .Values.replicaOverrides }}
        envFrom:
        {{- range .Values.envFromConfigMap }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.replicaOverrides }}
        # Load per-replica ConfigMaps - application uses STATEFULSET_REPLICA_INDEX to select config
        {{- range $replicaIndex, $override := .Values.replicaOverrides }}
        {{- if $override.env }}
        - configMapRef:
            name: {{ include "openclaw.fullname" $ }}-replica-{{ $replicaIndex }}-config
            optional: true
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.envFromSecret }}
        {{- if not (or .Values.envFromConfigMap .Values.replicaOverrides) }}
        envFrom:
        {{- end }}
        {{- range .Values.envFromSecret }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if and .Values.existingSecret.name .Values.existingSecret.keys }}
        {{- range $envVarName, $secretKey := .Values.existingSecret.keys }}
        - name: {{ $envVarName }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.existingSecret.name }}
              key: {{ $secretKey }}
        {{- end }}
        {{- else if and .Values.secret.enabled .Values.secret.data }}
        {{- range $key, $value := .Values.secret.data }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ include "openclaw.secretName" $ }}
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- if .Values.command }}
        command:
        {{- range .Values.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.extraArgs }}
        args:
        {{- range .Values.extraArgs }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.env.DATA_DIR | default "/data" }}
        {{- if and .Values.gateway .Values.gateway.controlUi .Values.gateway.controlUi.allowInsecureAuth }}
        - name: data
          mountPath: /home/node/.openclaw
          subPath: .openclaw
        {{- end }}
        {{- if .Values.extraVolumeMounts }}
        {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if and (not .Values.persistence.enabled) .Values.gateway .Values.gateway.controlUi .Values.gateway.controlUi.allowInsecureAuth }}
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- if .Values.livenessProbe.tcpSocket }}
          tcpSocket:
            {{- toYaml .Values.livenessProbe.tcpSocket | nindent 12 }}
          {{- else if .Values.livenessProbe.httpGet }}
          {{- toYaml .Values.livenessProbe.httpGet | nindent 10 }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- if .Values.readinessProbe.tcpSocket }}
          tcpSocket:
            {{- toYaml .Values.readinessProbe.tcpSocket | nindent 12 }}
          {{- else if .Values.readinessProbe.httpGet }}
          {{- toYaml .Values.readinessProbe.httpGet | nindent 10 }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if or (and (not .Values.persistence.enabled) .Values.gateway .Values.gateway.controlUi .Values.gateway.controlUi.allowInsecureAuth) .Values.extraVolumes }}
      volumes:
      {{- if and (not .Values.persistence.enabled) .Values.gateway .Values.gateway.controlUi .Values.gateway.controlUi.allowInsecureAuth }}
      - name: gateway-config-source
        configMap:
          name: {{ include "openclaw.fullname" . }}-gateway-config
      - name: openclaw-config
        emptyDir: {}
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "openclaw.selectorLabels" . | nindent 8 }}
      {{- with .Values.persistence.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
